### ISSUE TITLE
Should password hashing helper functions use base64 encoding?

### ISSUE THREAD

**Issue by mammothbane** [michaelklishin/rabbit-hole#159] opened 2020-07-15 12:27 UTC
I tried using the password hashing functions provided by this package, but RabbitMQ was rejecting them (Rabbit v3.8.x). I reimplemented these functions myself, and I discovered that RabbitMQ doesn't understand base64 url encoding.

I'd make a PR, but there seem to be tests that should cover this, so I'm not sure if this is an incompatibility between RabbitMQ versions, and I don't have the time in the short term to sort that out.

**Comment by michaelklishin** [comment] 2020-07-15 16:11
I cannot comment on what may be going on since you haven't provided any examples.

RabbitMQ HTTP API endpoint that creates or updates user records hasn't changed since 3.6.7 or so, https://github.com/rabbitmq/rabbitmq-management/commit/44c1a5e35964ab63eb5256112bbc8beee70653c3#diff-c4fc8e74da6d82775c07e60925c441db is the most recent meaningful change.

There are [`rabbitmqadmin` tests](https://github.com/rabbitmq/rabbitmq-management/blob/3ed83133c25c78829590ce5ca7d88627c61d130a/test/rabbit_mgmt_rabbitmqadmin_SUITE.erl#L217) for the endpoint that do use base64.

The function that endpoint relies on, [this one](https://github.com/rabbitmq/rabbitmq-server/blob/master/src/rabbit_auth_backend_internal.erl#L640), does not perform any Base64-encoding.

**Comment by michaelklishin** [comment] 2020-07-15 17:09
I [cannot reproduce](https://github.com/michaelklishin/rabbit-hole/commit/8acca21366db5d1def30ecb00a9cbfe3a93dc892). Most likely your code performed double base64 encoding or something of that kind. Closing unless actual evidence is posted.

**Closed by michaelklishin** 2020-07-15 17:09 UTC

**Comment by michaelklishin** [comment] 2020-07-16 00:51
For a reason that escapes me, the new tests fail on Go `1.13` and `tip` but not on `1.14`.

**Comment by michaelklishin** [comment] 2020-07-16 01:02
This was due to my attempt at addressing #160.
